config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "request_leaves#index"

  resources :addresses 

  resources :request_leaves
  get "total_request" , to: "request_leaves#total_request" 
  	
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :addressable, polymorphic: true

	geocoded_by :full_address, latitude: :lat, longitude: :lon
	after_validation :geocode 
	

	def full_address
		[street, city, state].compact.join(', ')
  end	
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request_leave.rb
class RequestLeave < ApplicationRecord
	belongs_to :user
	STATUS = {
    Pending: 0,
    Decline: 1,
    Approve: 2
  }.freeze

  enum status: STATUS
	
	
end

app/models/user.rb
class User < ApplicationRecord
	has_one :address, as: :addressable
	has_many :request_leaves
	accepts_nested_attributes_for :address
	mount_uploader :image, ProfileUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters  

	  devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :mobile_number,:gender,:image, address_attributes: [:id, :city, :state, :street, :pin_code, :country, :latitude ,:longitude])}
	 
	  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :mobile_number,:gender, :image)}
	end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
  def index
  end
end

app/controllers/request_leaves_controller.rb
class RequestLeavesController < ApplicationController
	def index       
    @requests = RequestLeave.all
  end
  # New action for creating post
  def new
    @request = RequestLeave.new()        
  end

  def create  	
    @request = RequestLeave.new(request_params)
    if @request.save
      redirect_to @request
    else
      render :new
    end
  end

  def show
  	@request = RequestLeave.find(params[:id])
  end

  def total_request
    @leave = current_user.request_leaves
  end

  private
  def request_params
  	params.require(:request_leave).permit(:leave_type, :description, :user_id).merge(user: current_user)   	
  end

  # def find_request
  #   @request = RequestLeave.find(params[:id])
  # end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
    
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/request_leaves_helper.rb
module RequestLeavesHelper
end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>  </title>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Leave Management', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>     
            <li style="color: white">Welcome <%= current_user.name %></li> 
            <li><%= link_to 'Check Status', total_request_path %></li>
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>       
        <% elsif %>          
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %> 
      </ul>
    </div>
  </div>
</nav>
</body>
</html>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leave</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag 'style' %>
    <!-- <script src="//maps.google.com/maps/api/js?key= AIzaSyDvqqU18es0jXOxT7o5fJMoQbPcWReHAg0"></script>   -->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


   <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/leaves/index.html.erb
<h3>
	Map
</h3>


<div style='width: 800px;'>  
  <div id="map" style='width: 800px; height: 400px;'></div>  
</div>  

<script type="text/javascript">  
handler = Gmaps.build('Google');  
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){  
  markers = handler.addMarkers([  
    {  
      "lat": 37.3333945,  
      "lng": -121.8806499,  
      "picture": {  
        "width":  32,  
        "height": 32  
      },  
      "infowindow": "SJSU"  
    }  
  ]);  
  handler.bounds.extendWith(markers);  
  handler.fitMapToBounds();  
});  
</script>

app/views/request_leaves/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
   Leave Request
  </title>
</head>
<body>
	
	<% if user_signed_in? %>	
	<div class="container">
		<h3>Apply for leave</h3>    
		<%= form_with model: RequestLeave.new do |form| %>
		  <div  class="form-group">
		    <p>
			    <b>Leave Type</b><br />
			    <%= form.radio_button :leave_type, 'Casual Leave' %> Casual Leave<br />
			    <%= form.radio_button :leave_type, 'Maternity Leave' %> Maternity Leave<br />
			    <%= form.radio_button :leave_type, 'Parental leave' %> Parental leave<br />
			    <%= form.radio_button :leave_type, 'Leave Without Pay' %> Leave Without Pay<br/>
				</p>
		  </div>

		  <div>
		    <%= form.label :description %><br>
		    <%= form.text_area :description %><br>      
		  </div>
		  		  
		  <div>
		    <%= form.submit %>
		  </div>
		<% end %>		
	</div>
	<% end %>	
</body>
</html>

app/views/request_leaves/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
		table, th, td 
		 {
		  border: 1px solid #ddd;
		  padding: 8px;
		}

		.center {
		  margin-left: auto;
		  margin-right: auto;
		}

		th {
		  padding-top: 12px;
		  padding-bottom: 12px;
		  text-align: left;
		  background-color: #4CAF50;
		  color: white;
		}

	</style>
</head>
<body>
	<h2 class="text-center">
		Leave Status
	</h2>
<div>
	<table class="center">
		<tr>
		<th>
			Leave Type
		</th>			
		<th>
			Description
		</th>
		<th>
			status
		</th>		
	</tr>		 
	<tr>
		<td>
			<%= @request.leave_type%>
		</td>
		<td>
			<%= @request.description%>
		</td>		
		<td>
			<%= @request.status %>
 		</td>		
	</tr> 	
	</table>    
</div>
</body>
</html>

app/views/request_leaves/total_request.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
		table, th, td 
		 {
		  border: 1px solid #ddd;
		  padding: 8px;
		}

		.center {
		  margin-left: auto;
		  margin-right: auto;
		  font-family: Arial, Helvetica, sans-serif;
		}

		th {
		  padding-top: 12px;
		  padding-bottom: 12px;
		  text-align: left;
		  background-color: #684A43;
		  color: white;
		}
		#requests tr:nth-child(even){background-color: #f2f2f2;}

		#requests tr:hover {background-color: #ddd;}

	</style>
</head>
<body>	
<div>
	<table class="center" id="requests">
		<h2 class="text-center">
		Leave Status
	</h2>
		<tr>
		<th>
			Leave Type
		</th>			
		<th>
			Description
		</th>
		<th>
			status
		</th>		
		<th>
			Action
		</th>	
	</tr>
	 	<% @leave.all.each do |request| %> 
			<tr>
				<td>
					<%= request.leave_type%>
				</td>
				<td>
					<%= request.description%>
				</td>		
				<td>
					<%= request.status %>
		 		</td>	
		 		<td>
		 			<%= link_to 'Show' , request_leave_path(request)  %>
		 		</td>	
			</tr> 
		<% end %>			
	</table>    
</div>
</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>